import { Product } from '@/models/product.model';
import { RouteConfig } from '.';

type ProductConfig = {
  [key: string]: Product;
};

export const ProductConfigs: ProductConfig = {
  revel: {
    id: 'revel',
    name: 'Revel',
    logo: '/images/service-logos/revel-color.png',
    images: [
      '/images/equipments/Revel/Revel (1).jpeg',
      '/images/equipments/Revel/Revel (2).png',
      '/images/equipments/Revel/Revel (3).jpg',
      '/images/equipments/Revel/Revel (4).png',
      '/images/equipments/Revel/Revel (5).jpg',
    ],
    route: RouteConfig.Revel,
  },
  toast: {
    id: 'toast',
    name: 'Toast',
    logo: '/images/service-logos/toast-color.png',
    route: RouteConfig.Toast,
    images: [
      '/images/equipments/Toast/Toast (1).jpg',
      '/images/equipments/Toast/Toast (2).png',
      '/images/equipments/Toast/Toast (3).png',
      '/images/equipments/Toast/Toast (4).png',
      '/images/equipments/Toast/Toast (5).png',
      '/images/equipments/Toast/Toast (6).webp',
      '/images/equipments/Toast/Toast (7).jpg',
      '/images/equipments/Toast/Toast (8).jpg',
    ],
  },
  union: {
    id: 'union',
    name: 'Union',
    logo: '/images/service-logos/union-color.png',
    route: RouteConfig.Union,
    images: [
      '/images/equipments/Union/Union (1).jpeg',
      '/images/equipments/Union/Union (2).png',
      '/images/equipments/Union/Union (3).png',
      '/images/equipments/Union/Union (4).png',
      '/images/equipments/Union/Union (5).png',
    ],
  },
  brink: {
    id: 'brink',
    name: 'Brink',
    logo: '/images/service-logos/brink-color.png',
    route: RouteConfig.Brink,
    images: ['/images/equipments/Brick/Brick-01.png'],
  },
  cloverflex: {
    id: 'cloverflex',
    name: 'Clover Flex',
    logo: '/images/service-logos/clover-color.png',
    route: RouteConfig.CloverFlex,
    images: [
      '/images/equipments/Clover Flex/Clover Flex (1).jpg',
      '/images/equipments/Clover Flex/Clover Flex (2).jpg',
      '/images/equipments/Clover Flex/Clover Flex (3).png',
      '/images/equipments/Clover Flex/Clover Flex (4).webp',
      '/images/equipments/Clover Flex/Clover Flex (5).png',
      '/images/equipments/Clover Flex/Clover Flex (6).webp',
    ],
  },
  rpower: {
    id: 'rpower',
    name: 'Rpower',
    logo: '/images/service-logos/rpower-color.png',
    route: RouteConfig.Rpower,
    images: [
      '/images/equipments/Rpower/Rpower (1).png',
      '/images/equipments/Rpower/Rpower (2).png',
    ],
  },
  touchbistro: {
    id: 'touchbistro',
    name: 'Touch Bistro',
    logo: '/images/service-logos/touch-color.png',
    route: RouteConfig.Touchbistro,
    images: [
      '/images/equipments/TouchBistro/TouchBistro (1).jpg',
      '/images/equipments/TouchBistro/TouchBistro (2).webp',
      '/images/equipments/TouchBistro/TouchBistro (3).png',
      '/images/equipments/TouchBistro/TouchBistro (4).png',
      '/images/equipments/TouchBistro/TouchBistro (5).webp',
      '/images/equipments/TouchBistro/TouchBistro (6).png',
    ],
  },
  exatouch: {
    id: 'exatouch',
    name: 'Exatouch',
    logo: '/images/service-logos/exatouch-color.png',
    route: RouteConfig.Exatouch,
    images: [
      '/images/equipments/Exatouch/Exatouch (1).png',
      '/images/equipments/Exatouch/Exatouch (2).png',
      '/images/equipments/Exatouch/Exatouch (3).png',
      '/images/equipments/Exatouch/Exatouch (4).jpg',
    ],
  },
  simphony: {
    id: 'simphony',
    name: 'Simphony',
    logo: '/images/service-logos/micros-color.png',
    route: RouteConfig.Simphony,
    images: [
      '/images/equipments/Simphony/Simphony (1).jpg',
      '/images/equipments/Simphony/Simphony (2).jpg',
      '/images/equipments/Simphony/Simphony (3).jpg',
      '/images/equipments/Simphony/Simphony (4).jpg',
      '/images/equipments/Simphony/Simphony (5).png',
      '/images/equipments/Simphony/Simphony (6).webp',
      '/images/equipments/Simphony/Simphony (7).png',
      '/images/equipments/Simphony/Simphony (8).avif',
    ],
  },
  aldelo: {
    id: 'aldelo',
    name: 'Aldelo',
    logo: '/images/service-logos/aldelo-color.png',
    route: RouteConfig.Aldelo,
    images: [
      '/images/equipments/Aldelo/Aldelo (1).jpg',
      '/images/equipments/Aldelo/Aldelo (2).jpg',
      '/images/equipments/Aldelo/Aldelo (3).jpg',
      '/images/equipments/Aldelo/Aldelo (3).png',
      '/images/equipments/Aldelo/Aldelo (4).jpg',
      '/images/equipments/Aldelo/Aldelo (5).png',
    ],
  },
  lightspeed: {
    id: 'lightspeed',
    name: 'LightSpeed',
    logo: '/images/service-logos/lightspeed-color.png',
    route: RouteConfig.Lightspeed,
    images: [
      '/images/equipments/Lightspeed/Lightspeed (1).jpeg',
      '/images/equipments/Lightspeed/Lightspeed (10).webp',
      '/images/equipments/Lightspeed/Lightspeed (11).avif',
      '/images/equipments/Lightspeed/Lightspeed (2).jpg',
      '/images/equipments/Lightspeed/Lightspeed (3).jpg',
      '/images/equipments/Lightspeed/Lightspeed (4).webp',
      '/images/equipments/Lightspeed/Lightspeed (5).webp',
      '/images/equipments/Lightspeed/Lightspeed (6).jpg',
      '/images/equipments/Lightspeed/Lightspeed (7).png',
      '/images/equipments/Lightspeed/Lightspeed (8).webp',
      '/images/equipments/Lightspeed/Lightspeed (9).webp',
    ],
  },
  clover: {
    id: 'clover',
    name: 'Clover',
    logo: '/images/service-logos/clover-duo-color.png',
    route: RouteConfig.CloverDuo,
    images: [
      '/images/equipments/Clover/Clover (1).jpg',
      '/images/equipments/Clover/Clover (2).jpg',
      '/images/equipments/Clover/Clover (3).jpg',
      '/images/equipments/Clover/Clover (4).webp',
      '/images/equipments/Clover/Clover (5).webp',
    ],
  },
  ovvi: {
    id: 'ovvi',
    name: 'Ovvi',
    logo: '/images/service-logos/ovvi-color.png',
    route: RouteConfig.Ovvi,
    images: [
      '/images/equipments/Ovvi/Ovvi (1).jpeg',
      '/images/equipments/Ovvi/Ovvi (2).png',
      '/images/equipments/Ovvi/Ovvi (3).jpg',
      '/images/equipments/Ovvi/Ovvi (4).png',
      '/images/equipments/Ovvi/Ovvi (5).jpg',
    ],
  },
  aloha: {
    id: 'aloha',
    name: 'Aloha',
    logo: '/images/service-logos/aloha-color.png',
    route: RouteConfig.Aloha,
    images: [
      '/images/equipments/Aloha/Aloha (1).jpg',
      '/images/equipments/Aloha/Aloha (2).jpg',
      '/images/equipments/Aloha/Aloha (3).jpg',
      '/images/equipments/Aloha/Aloha (4).png',
      '/images/equipments/Aloha/Aloha (5).webp',
    ],
  },
  upserve: {
    id: 'upserve',
    name: 'Upserve',
    logo: '/images/service-logos/upserve-color.png',
    route: RouteConfig.Upserve,
    images: [
      '/images/equipments/Upserve/Upserve (1).jpg',
      '/images/equipments/Upserve/Upserve (2).png',
      '/images/equipments/Upserve/Upserve (3).png',
      '/images/equipments/Upserve/Upserve (4).png',
      '/images/equipments/Upserve/Upserve (5).webp',
      '/images/equipments/Upserve/Upserve (6).jpg',
      '/images/equipments/Upserve/Upserve (7).webp',
    ],
  },
};
