export enum RouteConfig {
  Home = '/',
  GetPricing = '/get-pricing',
  Solution = '/solutions',
  Contacts = '/contacts',
  Faqs = '/faqs',
  Blogs = '/blogs',
  Calculator = '/credit-card-processing-calculator',
  PrivacyPolicy = '/privacy-policy',
  TermsOfService = '/terms-of-service',
  BusinessTypes = '/business',
  Products = '/products',
  Equipment = '/pos-equipments',
  // Business
  FullServiceRestaurants = '/full-service-restaurants',
  Retail = '/retail',
  QuickServiceRestaurants = '/quick-service-restaurants',
  SmallBusiness = '/small-business',
  BarsAndNightClubs = '/bars-and-night-clubs',
  Pizzerias = '/pizzerias',
  // Equipment
  Revel = '/revel',
  CloverFlex = '/clover-flex',
  CloverDuo = '/clover-duo',
  Exatouch = '/exatouch',
  Simphony = '/simphony',
  Brink = '/brink',
  Ovvi = '/ovvi',
  Aldelo = '/aldelo',
  Lightspeed = '/lightspeed',
  Aloha = '/aloha',
  Upserve = '/upserve',
  Toast = '/toast',
  Rpower = '/rpower',
  Union = '/union',
  Touchbistro = '/touchbistro',
  // Products
  CloverAppMarket = '/clover-app-market',
  CashDiscountProgram = '/cash-discount-program',
  GiftCardProgram = '/gift-card-program',
  CustomerLoyaltyProgramsAndRewards = '/customer-loyalty-programs-and-rewards',
  OnlineAnalytics = '/online-analytics',
  CheckServices = '/check-services',
  CashAdvance = '/cash-advance',
  QuickbooksPlugin = '/quickbooks-plugin',
  Invoicing = '/invoicing',
  Partner = '/partner',
  PaymentProcessing = '/payment-processing',
  AboutUs = '/about-us',
  SaleSystems = '/point-of-sale-systems',
  MobileCard = '/solutions/mobile-card',
  CreditCard = '/solutions/credit-card',
  OnlineProcessing = '/solutions/online-processing',
  Funding = '/same-day-funding',
  CashBonusCalculator = '/cash-signing-bonus-calculator',
}

export type RouteConfigType = `${RouteConfig}`;
