export enum RouteConfig {
  Home = '/',
  GetPricing = '/get-pricing',
  Solution = '/solutions',
  Contacts = '/contacts',
  Faqs = '/faqs',
  Blogs = '/blogs',
  Calculator = '/credit-card-processing-calculator',
  PrivacyPolicy = '/privacy-policy',
  TermsOfService = '/terms-of-service',
  BusinessTypes = '/business',
  Products = '/product',
  Equipment = '/pos-equipments',
  // Business
  FullServiceRestaurants = '/full-service-restaurants',
  Retail = '/retail',
  QuickServiceRestaurants = '/quick-service-restaurants',
  SmallBusiness = '/small-business',
  BarsAndNightClubs = '/bars-and-night-clubs',
  Pizzerias = '/pizzerias',
  // Equipment
  Revel = '/product/revel',
  CloverFlex = '/product/clover-flex',
  CloverDuo = '/product/clover-duo',
  Exatouch = '/product/exatouch',
  Simphony = '/product/simphony',
  Brink = '/product/brink',
  Ovvi = '/product/ovvi',
  Aldelo = '/product/aldelo',
  Lightspeed = '/product/lightspeed',
  Aloha = '/product/aloha',
  Upserve = '/product/upserve',
  Toast = '/product/toast',
  Rpower = '/product/rpower',
  Union = '/product/union',
  Touchbistro = '/product/touchbistro',
  // Products
  CloverAppMarket = '/clover-app-market',
  CashDiscountProgram = '/cash-discount-program',
  GiftCardProgram = '/gift-card-program',
  CustomerLoyaltyProgramsAndRewards = '/customer-loyalty-programs-and-rewards',
  OnlineAnalytics = '/online-analytics',
  CheckServices = '/check-services',
  CashAdvance = '/cash-advance',
  QuickbooksPlugin = '/quickbooks-plugin',
  Invoicing = '/invoicing',
  Partner = '/partner',
  PaymentProcessing = '/payment-processing',
  AboutUs = '/about-us',
  SaleSystems = '/point-of-sale-systems',
  MobileCard = '/solutions/mobile-card',
  CreditCard = '/solutions/credit-card',
  OnlineProcessing = '/solutions/online-processing',
  CashBonusCalculator = '/cash-signing-bonus-calculator',
  SameDayFunding = '/same-day-funding',
  POSSystems = '/pos-systems',
  SuggestPos = '/suggest-pos',
  RequestDemo = '/request-demo-pos',
}

export type RouteConfigType = `${RouteConfig}`;
